import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { fetchStaffQueue, type StaffQueueItem } from '../services/api';

const priorities = ['', 'LOW', 'MEDIUM', 'HIGH'];
const statuses = ['', 'NEW', 'OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];
export default function StaffQueuePage() {
  const [items, setItems] = useState<StaffQueueItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState(''); const [ownerState, setOwnerState] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const data = await fetchStaffQueue({ search, status, requestedPriority: priority, ownerState: ownerState as 'assigned' | 'unassigned' | undefined, page, pageSize: 10 }); setItems(data.items); setTotal(data.pagination.totalItems); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to fetch the IT Staff Queue.'); } finally { setLoading(false); } }, [search, status, priority, ownerState, page]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  const clear = () => { setSearch(''); setStatus(''); setPriority(''); setOwnerState(''); setPage(1); };
  return <div className="max-w-7xl mx-auto p-4 md:p-8"><div className="flex justify-between items-center mb-6"><div><h1 className="text-2xl font-bold text-[#1A2E22]">My Queue</h1><p className="text-sm text-[#4A6355]">{total} ticket{total === 1 ? '' : 's'} available</p></div><button onClick={clear} className="text-sm text-[#006B3C] font-semibold">Clear filters</button></div><div className="bg-white border border-[#D1E0D8] rounded-xl p-4 grid gap-3 md:grid-cols-4"><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search ticket, requester, owner…" className="md:col-span-2 border rounded-lg p-2" />{[[status, setStatus, statuses, 'Status'], [priority, setPriority, priorities, 'Requested priority'], [ownerState, setOwnerState, ['', 'unassigned', 'assigned'], 'Owner']].map(([value, setter, options, label]) => <select key={String(label)} value={String(value)} onChange={e => { (setter as (v: string) => void)(e.target.value); setPage(1); }} className="border rounded-lg p-2">{(options as string[]).map(option => <option key={option} value={option}>{option || String(label)}</option>)}</select>)}</div>{loading ? <p className="p-8 text-center text-[#4A6355]">Loading Queue…</p> : error ? <div className="mt-4 p-4 bg-red-50 text-red-700 rounded-lg">{error} <button onClick={() => void load()} className="underline font-semibold">Retry</button></div> : items.length === 0 ? <p className="p-8 text-center text-[#4A6355]">{search || status || priority || ownerState ? 'No Tickets match the current search or filters.' : 'No Tickets are currently in the queue.'}</p> : <div className="mt-4 grid gap-3">{items.map(ticket => <article key={ticket.id} className="bg-white border border-[#D1E0D8] rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><Link to={`/staff/tickets/${ticket.ticketNumber}`} className="font-mono font-bold text-[#006B3C]">{ticket.ticketNumber}</Link><p className="font-semibold text-[#1A2E22]">{ticket.summary}</p><p className="text-sm text-[#4A6355]">{ticket.requester.name} · {ticket.ticketOwner?.name || 'Unassigned'}</p></div><div className="flex gap-2 text-xs font-semibold"><span className="px-2 py-1 bg-[#EAF6EF] rounded">{ticket.currentStatus}</span><span className="px-2 py-1 bg-amber-50 rounded">Req {ticket.requestedPriority}</span><span className="px-2 py-1 bg-blue-50 rounded">IT {ticket.itPriority}</span></div></article>)}</div>}<div className="flex justify-between mt-5"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="px-3 py-2 border rounded disabled:opacity-40">Previous</button><span className="text-sm">Page {page}</span><button disabled={items.length < 10} onClick={() => setPage(page + 1)} className="px-3 py-2 border rounded disabled:opacity-40">Next</button></div></div>;
}
